const String APP_STARTED = 'APP_STARTED';
const String AUTHENTICATED = 'AUTHENTICATED';
const String UN_AUTHENTICATED = 'UN_AUTHENTICATED';
const String LOGOUT = 'LOGOUT';
const String AUTH_LOADER = 'AUTH_LOADER';

// For Loging iN

const String INITIAL_LOGIN = 'INITIAL_LOGIN';
const String SUCCESS_LOGIN = 'SUCCESS_LOGIN';
const String FAILED_LOGIN = 'FAILED_LOGIN';
const String LOADING_LOGIN = 'LOADING_LOGIN';
const String NOT_APPROVE_LOGIN = 'NOT_APPROVE_LOGIN';
const String SET_PREFERENCE = 'SET_PREFERENCE';
